### PR TITLE
refactoring code in control contract

### PR DESCRIPTION
**Pull request by CryptoBadBoy**
Removing unnecessary debug data, refactoring

### CODE REVIEW

**Comment by amurdev** [comment]
Not approved

**Comment by CryptoBadBoy** [comment]
@amurdev, Do not close this pull request

**Comment by amurdev** [comment]
such commit messages are not permitted, please be polite

**Comment by CryptoBadBoy** [comment]
@amurdev , You are not a developer. Come to your senses

**Pull request closed without merging**
